name = "flaregram"
main = "src/index.js"
compatibility_date = "2023-05-18"
usage_model = "bundled"
env = { }

[dev]
host = "localhost"

[vars]
########## flaregram ###########
#  ---- See Wiki for all env variable descriptions.

# Mandatory Variables
REPO_VERSION = "1.0.1"
BOT_TOKEN = ""
WEBHOOK_URL = ""

# Optional Variables
SECRET_TOKEN = ""
DROP_PENDING_UPDATES = "True"

##################################
